# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1
orbs:
  wp-product-orb: wpengine/wp-product-orb@1.3.0
  php: circleci/php@1.1.0

jobs:
  checkout:
    executor: wp-product-orb/default
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  plugin-cms-team-plugin-checkout:
    executor: wp-product-orb/default
    working_directory: ~/project/plugins/cms-team-plugin
    environment:
      WPE_SESSION_DIR: ./.wpe
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Make artifacts build directory
          command: |
            [ ! -d "build" ] && mkdir build &>/dev/null
      - wp-product-orb/get-version-from-php:
          filename: headless-poc.php
          return_var: BUILD_VERSION
      - wp-product-orb/variable:
          var: BUILD_VERSION
          value: $BUILD_VERSION
      - persist_to_workspace:
          root: ~/project
          paths:
            - plugins/cms-team-plugin

  plugin-cms-team-plugin-composer:
    executor: php/default
    working_directory: ~/project/plugins/cms-team-plugin
    steps:
      - attach_workspace:
          at: ~/project
      - php/install-composer
      - php/install-packages:
          app-dir: .
      - run:
          name: Composer PHP lint and code sniffer
          command: |
            /usr/local/bin/composer suite
          working_directory: .
      - persist_to_workspace:
          root: ~/project
          paths:
            - plugins/cms-team-plugin

  plugin-cms-team-plugin-bundle-zip:
    executor: wp-product-orb/default
    working_directory: ~/project/plugins/cms-team-plugin
    environment:
      WPE_SESSION_DIR: ./.wpe
    steps:
      - attach_workspace:
          at: ~/project
      - wp-product-orb/variable-load
      - run:
          name: "Bundle plugin files into a zip"
          command: |
            cd ..
            zip --verbose -x@cms-team-plugin/.zipignore -x *.wpe/* -r "cms-team-plugin/build/headless-poc.$BUILD_VERSION.zip" cms-team-plugin
      - store_artifacts:
          path: build
      - persist_to_workspace:
          root: ~/project
          paths:
            - plugins/cms-team-plugin/build

  plugin-cms-team-plugin-bundle-json:
    executor: wp-product-orb/parser
    working_directory: ~/project/plugins/cms-team-plugin
    environment:
      WPE_SESSION_DIR: ./.wpe
    steps:
      - attach_workspace:
          at: ~/project
      - wp-product-orb/variable-load
      - wp-product-orb/parse-wp-readme:
          infile: readme.txt
          outfile: build/headless-poc.$BUILD_VERSION.json
      - store_artifacts:
          path: build
      - persist_to_workspace:
          root: ~/project
          paths:
            - plugins/cms-team-plugin/build

  plugin-cms-team-plugin-deploy-staging:
    executor: wp-product-orb/authenticate
    working_directory: ~/project/plugins/cms-team-plugin
    environment:
      WPE_SESSION_DIR: ./.wpe
    steps:
      - attach_workspace:
          at: ~/project
      - wp-product-orb/variable-load
      - wp-product-orb/authenticate:
          user: WPE_LDAP_USER
          pass: WPE_LDAP_PASS
          url: https://auth-staging.wpengine.io/v1/tokens
      - wp-product-orb/post-zip:
          url: https://wp-product-info-staging.wpesvc.net/v1/plugins/headless-poc
          zip: build/headless-poc.$BUILD_VERSION.zip
          json: build/headless-poc.$BUILD_VERSION.json
          version: $BUILD_VERSION

workflows:
  plugin-cms-team-plugin:
    jobs:
      - checkout
      - plugin-cms-team-plugin-checkout:
          requires:
            - checkout
      - plugin-cms-team-plugin-composer:
          requires:
            - plugin-cms-team-plugin-checkout
      - plugin-cms-team-plugin-bundle-zip:
          requires:
            - plugin-cms-team-plugin-checkout
      - plugin-cms-team-plugin-bundle-json:
          requires:
            - plugin-cms-team-plugin-checkout
      - plugin-cms-team-plugin-deploy-staging:
          requires:
            - plugin-cms-team-plugin-bundle-zip
            - plugin-cms-team-plugin-bundle-json
          filters:
            branches:
              only: main
          context: wpe-ldap-creds
