# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1
orbs:
  wp-product-orb: wpengine/wp-product-orb@1.3.0
  php: circleci/php@1.1.0

parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true

  # A parameter per package
  wpe-headless-plugin:
    type: boolean
    default: false

jobs:
  trigger-workflows:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          # See MarkKelnar about the personal api token created and added as an environment variable for the project
          name: Set token
          command: echo "export CIRCLE_USER_TOKEN=${CIRCLE_PROJECT_TOKEN}" >> $BASH_ENV
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/monorepo.sh && .circleci/monorepo.sh
          environment:
            # (optional) print additional debug information
            MONOREPO_DEBUG: "true"
            # (optional) additional CI parameters to include in the pipeline (must be a valid JSON)
            # CI_PARAMETERS: '{ "deploy": true }'

  checkout:
    executor: wp-product-orb/default
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  plugin-wpe-headless-checkout:
    executor: wp-product-orb/default
    working_directory: ~/project/plugins/wpe-headless
    environment:
      WPE_SESSION_DIR: ./.wpe
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Make artifacts build directory
          command: |
            [ ! -d "build" ] && mkdir build &>/dev/null
      - wp-product-orb/get-version-from-php:
          filename: headless-poc.php
          return_var: BUILD_VERSION
      - wp-product-orb/variable:
          var: BUILD_VERSION
          value: $BUILD_VERSION
      - persist_to_workspace:
          root: ~/project
          paths:
            - plugins/wpe-headless

  plugin-wpe-headless-composer:
    executor: php/default
    working_directory: ~/project/plugins/wpe-headless
    steps:
      - attach_workspace:
          at: ~/project
      - php/install-composer
      - php/install-packages:
          app-dir: .
      - run:
          name: Composer PHP lint and code sniffer
          command: |
            # /usr/local/bin/composer suite
          working_directory: .
      - persist_to_workspace:
          root: ~/project
          paths:
            - plugins/wpe-headless

  plugin-wpe-headless-bundle-zip:
    executor: wp-product-orb/default
    working_directory: ~/project/plugins/wpe-headless
    environment:
      WPE_SESSION_DIR: ./.wpe
    steps:
      - attach_workspace:
          at: ~/project
      - wp-product-orb/variable-load
      - run:
          name: "Bundle plugin files into a zip"
          command: |
            cd ..
            zip --verbose -x@wpe-headless/.zipignore -x *.wpe/* */build/ -r "wpe-headless/build/headless-poc.$BUILD_VERSION.zip" wpe-headless
      - store_artifacts:
          path: build
      - persist_to_workspace:
          root: ~/project
          paths:
            - plugins/wpe-headless/build

  plugin-wpe-headless-bundle-json:
    executor: wp-product-orb/parser
    working_directory: ~/project/plugins/wpe-headless
    environment:
      WPE_SESSION_DIR: ./.wpe
    steps:
      - attach_workspace:
          at: ~/project
      - wp-product-orb/variable-load
      - wp-product-orb/parse-wp-readme:
          infile: readme.txt
          outfile: build/headless-poc.$BUILD_VERSION.json
      - store_artifacts:
          path: build
      - persist_to_workspace:
          root: ~/project
          paths:
            - plugins/wpe-headless/build

  plugin-wpe-headless-deploy-staging:
    executor: wp-product-orb/authenticate
    working_directory: ~/project/plugins/wpe-headless
    environment:
      WPE_SESSION_DIR: ./.wpe
    steps:
      - attach_workspace:
          at: ~/project
      - wp-product-orb/variable-load
      - wp-product-orb/authenticate:
          user: WPE_LDAP_USER
          pass: WPE_LDAP_PASS
          url: https://auth-staging.wpengine.io/v1/tokens
      - wp-product-orb/post-zip:
          url: https://wp-product-info-staging.wpesvc.net/v1/plugins/headless-poc
          zip: build/headless-poc.$BUILD_VERSION.zip
          json: build/headless-poc.$BUILD_VERSION.json
          version: $BUILD_VERSION

workflows:
  version: 2

  # The main workflow responsible for triggering all other workflows
  # in which changes are detected.
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows

  # Workflows defined for each package.
  plugin-wpe-headless:
    when: << pipeline.parameters.wpe-headless-plugin >>
    jobs:
      - checkout
      - plugin-wpe-headless-checkout:
          requires:
            - checkout
      - plugin-wpe-headless-composer:
          requires:
            - plugin-wpe-headless-checkout
      - plugin-wpe-headless-bundle-zip:
          requires:
            - plugin-wpe-headless-checkout
      - plugin-wpe-headless-bundle-json:
          requires:
            - plugin-wpe-headless-checkout
      - plugin-wpe-headless-deploy-staging:
          requires:
            - plugin-wpe-headless-bundle-zip
            - plugin-wpe-headless-bundle-json
          filters:
            branches:
              only: main
          context: wpe-ldap-creds
