blank_issues_enabled: false
contact_links:
  - name: Questions and help
    url: https://github.com/wpengine/faustjs/discussions/categories/q-a
    about: Ask a question or get help in GitHub Discussions
  - name: Ideas and feature requests
    url: https://github.com/wpengine/faustjs/discussions/categories/ideas
    about: Share ideas for new features or improvements in GitHub Discussions
  - name: Headless WordPress Discord
    url: https://discord.gg/J2khkF9XYK
    about: Chat with the Headless WordPress community
