name: 'Cache restoration'
description: 'Setup a NodeJS environment and restore cache if any, given a node version'

inputs:
  node-version:
    description: 'Node version to use, default to LTS'
    required: true
    default: 22
outputs:
  cache-hit:
    description: 'Forward actions/cache cache-hit output'
    value: ${{ steps.node-cache.outputs.cache-hit }}

runs:
  using: 'composite' # Mandatory parameter
  steps:
    # Setup a Node environment given a node version
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache Node Modules
      id: node-cache
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
      with:
        path: |
          **/node_modules
          ~/.cache
        key: ${{ runner.os }}-${{ inputs.node-version }}-${{ hashFiles('package-lock.json') }}
