name: 'Test Plugin Deploy'
description: 'Upload zip file to releases tab'
branding:
  icon: 'upload-cloud'
  color: 'blue'

outputs:
  zip-path:
    description: 'Path to zip file'
    value: ${{ steps.zip.outputs.zip-path }}
  org-zip-path:
    description: 'Path to .org zip file'
    value: ${{ steps.zip-org.outputs.zip-path }}

runs:
  using: 'composite'
  steps:
    - id: prepare
      name: Prepare Environment
      run: |
        sudo apt-get update && sudo apt-get install zip rsync -y
      shell: bash

    - id: zip
      name: Zip Plugin (Main)
      run: |
        # Create dist folder and copy files while excluding .distignore items
        mkdir -p dist
        rsync -av --exclude-from="${{ env.PLUGIN_DIR }}/.distignore" ${{ env.PLUGIN_DIR }}/ dist/${{ env.SLUG }}

        zip_file="faustwp-${{ env.VERSION }}.zip"
        zip -r "$zip_file" "dist/${{ env.SLUG }}"

        # Save zip path to output
        echo "::set-output name=zip-path::$PWD/$zip_file"
      shell: bash

    - id: zip-org
      name: Zip Plugin (.org version)
      run: |
        # Delete old directory
        rm -rf dist

        # Create dist folder and copy files while excluding .distignore items
        mkdir -p dist
        # Copy plugin files to dist folder and exclude external updater
        rsync -av --exclude-from="${{ env.PLUGIN_DIR }}/.distignore" --exclude="includes/updates/check-for-updates.php" --exclude="includes/updates/class-plugin-updater.php" "${{ env.PLUGIN_DIR }}/" "dist/${{ env.SLUG }}"

        # Updates for the CHANGELOG file
        sed -i -e 's/plugin updates from an external API endpoint./plugin updates from an external API endpoint when not installed from WordPress.org/' "dist/${{ env.SLUG }}/CHANGELOG.md"

        # Create .org zip file
        org_zip_file="faustwp-${{ env.VERSION }}.org.zip"
        zip -r "$org_zip_file" "dist/${{ env.SLUG }}"

        # Save zip path to output
        echo "::set-output name=zip-path::$PWD/$org_zip_file"
      shell: bash

    - id: debug-main
      name: Debug Check Main Zip File
      run: |
        echo "Main zip file path: ${{ steps.zip.outputs.zip-path }}"
        ls -lah ${{ steps.zip.outputs.zip-path }}
        unzip -l ${{ steps.zip.outputs.zip-path }}
      shell: bash

    - id: debug-org
      name: Debug Check .org Zip File
      run: |
        echo ".org zip file path: ${{ steps.zip-org.outputs.zip-path }}"
        ls -lah ${{ steps.zip-org.outputs.zip-path }}
        unzip -l ${{ steps.zip-org.outputs.zip-path }}
      shell: bash

    # - id: upload-main
    #   name: Upload Main Zip File to Release
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     files: ${{ steps.zip.outputs.zip-path }}
    #     asset_name: faustwp-${{ env.VERSION }}.zip
    #     overwrite: true

    # - id: upload-org
    #   name: Upload .org Zip File to Release
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     files: ${{ steps.zip-org.outputs.zip-path }}
    #     asset_name: faustwp-${{ env.VERSION }}.org.zip
    #     overwrite: true
