name: Check Dependencies

on:
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  check_depedencies:
    runs-on: ubuntu-latest
    steps:
      - name: checkout current branch
        uses: actions/checkout@v3
        with:
          ref: canary
          path: current

      - name: checkout proposed branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: proposed

      - name: set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: cd proposed && npm ci

      - name: compare lockfiles
        uses: ./proposed/.github/actions/compare-lockfiles
        with:
          current-lockfile-path: current
          proposed-lockfile-path: proposed
