# NOTE: This workflow is only to be used if the plugin needs to be deployed manually.
# Otherwise, changesets and the release-packages workflow should take care of 
# deploying the plugin automatically.
name: Deploy Plugin

on:
  workflow_dispatch:

jobs:
  deploy_plugin:
    name: Deploy Plugin
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
      with:
        # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
        fetch-depth: 0

    - name: Setup Node.js 16.x
      uses: actions/setup-node@master
      with:
        node-version: 16.x

    - name: Deploy plugin to WordPress.org
      # Use a variant of 10up/action-wordpress-plugin-deploy that allows us to specify a PLUGIN_DIR
      # to support our monorepo structure.
      uses: ./.github/actions/release-plugin
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        PLUGIN_DIR: plugins/faustwp
        SLUG: faustwp
