name: E2E Nightly Test

on:
  workflow_run:
    workflows: ["Nightly Releases"]
    types:
      - completed

jobs:
  e2e-nightly-test:
    name: E2E app on Node ${{ matrix.node }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: ['18', '20']
    defaults:
      run:
        working-directory: ./
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      # Install faust-scaffold-ts via npx create next app
      - name: npx create next app
        run: |
          npx create-next-app@13 \
            -e https://github.com/wpengine/faust-scaffold-ts/tree/main \
            --use-npm \
            e2e-app

      - name: Install nightly versions
        working-directory: e2e-app
        run: |
          npm install @faustwp/core@canary
          npm install @faustwp/cli@canary

      - name: copy env
        working-directory: e2e-app
        run: |
          cp .env.local.sample .env.local

      # Generate the schema to ensure no type collisions
      - name: Generate Schema
        working-directory: e2e-app
        run: |
          npm run generate

      - name: Build
        working-directory: e2e-app
        run: |
          npm run build
