name: E2E Test - Build
on: pull_request
jobs:
  e2e-test-generate-and-build:
    runs-on: ubuntu-latest
    env:
      PR_BRANCH: ${{github.event.pull_request.head.ref}}
    defaults:
      run:
        working-directory: ./
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: echo current pr branch name
      run: |
        echo $PR_BRANCH
    - name: npx create next app
      run: |
        npx create-next-app \
          -e https://github.com/wpengine/faustjs/tree/${PR_BRANCH} \
          --example-path examples/next/getting-started \
          --use-npm \
          testing-app
    # - name: Generate
    #   working-directory: testing-app
    #   run: |
    #     npm run generate
    - name: Build
      working-directory: testing-app
      run: |
        npm run build
