name: lint
on: pull_request
jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run eslint
      - run: npm install
      - run:  npm run lint
        continue-on-error: FALSE
