name: lint
on: pull_request
jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: NPM Install
        run: npm install
        env:
          CI: TRUE
      - name: Run eslint
        run:  npm run lint
        continue-on-error: FALSE
