name: ESLint
on: pull_request
jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install core dependencies
        run: npm install
        working-directory: packages/core
        env:
          CI: TRUE
      - name: Install react dependencies
        run: npm install
        working-directory: packages/react
        env:
          CI: TRUE
      - name: Install next dependencies
        run: npm install
        working-directory: packages/next
        env:
          CI: TRUE
      - name: Run eslint
        run:  npm run lint
        continue-on-error: FALSE
