name: ESLint
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node Dependencies
        run: npm install
        env:
          CI: TRUE
      - name: Linting
        run:  npm run lint
        continue-on-error: TRUE
