name: Post-release jobs

on:
  workflow_dispatch:
    inputs:
      published:
        description: "Simulates whether changesets did or did not publish a release."
        required: true
        default: "false"

jobs:
  simulate_output:
    name: "Simulate changesets/action output"
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.step1.outputs.published }}
    steps:
      - id: step1
        run: echo "::set-output name=published::${{ github.event.inputs.published }}"
  merge_to_main:
    name: "Merge `canary` into `main`"
    runs-on: ubuntu-latest
    needs: simulate_output
    if: ${{ needs.simulate_output.outputs.published == 'true' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Merge to main
        uses: actions/github-script@v5
        with:
          script: |
            const { mergeToMain } = require('.github/actions/post-release/index.js')
            return await mergeToMain({github, context})
