name: Release Packages

on:
  push:
    branches:
      - canary

permissions:
  contents: write      # For creating releases/tags and pushing tags
  pull-requests: write # For creating version PRs
  id-token: write      # For npm OIDC authentication

jobs:
  changesets:
    name: Manage Changesets
    runs-on: ubuntu-22.04
    outputs:
      has-changesets: ${{ steps.changesets.outputs.hasChangesets }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: npm ci

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          version: npm run version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish to npm
    needs: changesets
    if: needs.changesets.outputs.has-changesets == 'false'
    uses: ./.github/workflows/npm-publish.yml
    with:
      publish-command: changeset publish
      push-tags: true
