name: 🚀

on:
  push:
    tags:
      - '@faustwp/wordpress-plugin@*'
jobs:
  release_plugin:
    name: Deploy Plugin to WordPress.org
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: WordPress Plugin Deploy
        # Use a variant of 10up/action-wordpress-plugin-deploy that allows us to specify a PLUGIN_DIR
        # to support our monorepo structure.
        uses: ./.github/actions/release-plugin
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          PLUGIN_DIR: plugins/faustwp
          SLUG: faustwp
