name: test
on: pull_request
jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: npm install
      - run: npm run build
      - run: npm test
        continue-on-error: FALSE
