name: test
on: pull_request
jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bootstrap dependencies
        run: npm run bootstrap
        env:
          CI: TRUE
      - name: Run tests
        run:  npm run test
        continue-on-error: FALSE
