name: Test Packages

on:
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  unit-test_packages:
    name: "Test packages on Node.js ${{ matrix.node }} ${{ matrix.os }}"
    strategy:
      matrix:
        os: ['ubuntu-22.04']
        node: ['18', '20', '22']
    permissions:
      checks: write
      pull-requests: write
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Tests
        run: npm run test

      - name: Code Coverage for FaustWP Core Package
        uses: ./.github/actions/run-coverage
        with:
          working-directory: packages/faustwp-core

      - name: Code Coverage for FaustWP CLI Package
        uses: ./.github/actions/run-coverage
        with:
          working-directory: packages/faustwp-cli
